if(NOT INPUT OR NOT OUTPUT)
  message(FATAL_ERROR "INPUT and OUTPUT variables must be defined")
endif()

if(NOT EXISTS "${INPUT}")
  message(FATAL_ERROR "Input template file not found: ${INPUT}")
endif()

if(NOT EXISTS "${OUTPUT}")
  get_filename_component(CONFIG_DIRECTORY "${OUTPUT}" DIRECTORY)
  file(MAKE_DIRECTORY "${CONFIG_DIRECTORY}")
  get_filename_component(CLIENT_DIRECTORY "${CONFIG_DIRECTORY}" DIRECTORY)
  if(EXISTS "${CLIENT_DIRECTORY}/config.ini")
    file(RENAME "${CLIENT_DIRECTORY}/config.ini" "${OUTPUT}")
    return()
  endif()
  file(COPY_FILE "${INPUT}" "${OUTPUT}")
  message(STATUS "Seeded ${OUTPUT} from ${INPUT}")
endif()
